### ISSUE TITLE
Unable to into bootloader

### ISSUE THREAD

**Issue by AnalogDragon** [veroxzik/roxy-firmware#3]
I made the hardware for roxy-board，And it unable to into bootloader.Its crystal oscillator has no waveform, it seems that the initialization is not successful.

Not sure if it's a build problem or a burning problem.The bootloader elf I build in the attachment. 

I hope can upload the app and bootloader with .hex files.

[bootloader.zip](https://github.com/user-attachments/files/17393192/bootloader.zip)

**Comment by veroxzik** [comment]
Hi, I'm attaching the bootloader I use on my boards.
[bootloader_v1.1_2020-07-19.elf.zip](https://github.com/user-attachments/files/17451165/bootloader_v1.1_2020-07-19.elf.zip)
It appears to have differences with your file. Try it out and see if it works.

**Comment by AnalogDragon** [comment]
Thanks for reply.

I have tried your elf file, But it still not work. My operation is: first convert ELF to HEX file(use Keil_v5 bin/fromelf.exe), and then use STM32Cube Programmer to download it. The crystal stell no waveform and usb said recognized.

I tried to write a USB software myself, which only did USB enumeration and RCC initialization.The hardware is working.
May be something wrong with the ELF conversion process?

What should I do now? Maybe I can try the BIN file read from your chip？

**Comment by veroxzik** [comment]
Why do you convert to HEX? I feel like that is part of the issue.
STM32CubeProgrammer lets you write ELF directly, this is how I write to my boards.
![image](https://github.com/user-attachments/assets/9f3affaa-abc3-4c5f-8242-22dc0c65ac21)

**Comment by AnalogDragon** [comment]
You're right, I've solved the problem now.

I opened the roxy_v0.15.elf  with STM32 cube programmer before and found that it was read in BIN file format because I saw the ELF file header, So I mistakenly thought it could not parse the ELF file correctly.
![image](https://github.com/user-attachments/assets/9a26e1f9-18d4-4785-94e1-8dc2dd779809)

thank you again
